color: null
fieldLayouts:
  6e8b7625-f295-457b-a541-e459049f138a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-18T19:01:59+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a09d07ea-30e5-44fc-936a-1ccf06c16b7f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:03:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d56b297b-0f38-4dee-abc3-57498c544f41 # Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd7e9c80-98fa-435f-b7b8-dcce6d7069e1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-15T13:30:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3644b740-3500-418e-a08f-7e66e4a2b99e
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c24bec29-1fd4-4668-8c97-86a8fca94f57
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-15T13:30:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 89dec5ed-967b-4adc-96f4-990fe7f52da5
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae2220d3-6ace-4d4c-814b-4cafd0da637a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8757fe2d-7763-48e0-a556-3a66cfeba19f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-18T19:03:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1d7fd420-3fd4-4dc0-afca-1833e0d9a05c # SEOMatic Fields
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76de9c3c-1373-407a-b1d2-d51f84590b46
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:03:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 678939a0-3ca0-4044-b263-e25151ebb1df # Additional Header Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ece0be33-0e59-44cd-a40e-ef70c47da6d0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:03:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e4455cb-a3c6-4a1f-aece-f5b32088a23e # Additional Footer Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b7054eb-daf1-4588-adc6-48c9d6fb7e07
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: a681ecf9-eecf-4936-8233-c55a5885c08c
        userCondition: null
handle: resourcesPage
hasTitleField: true
icon: null
name: 'Resources Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
