color: null
description: null
fieldLayouts:
  243db469-6f40-4517-a75d-a7e8f81039f2:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:c24927ca-b97d-4582-af30-a791db8e082a'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-23T13:56:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bda4be51-a390-429b-856f-8ebd7905b00a
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b849859-e619-4c53-a923-33a7745ac886
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-23T13:56:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fcee80e9-4667-40be-9381-e2994ff56dc0 # Hero Headline
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c24927ca-b97d-4582-af30-a791db8e082a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-23T13:56:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 458fef22-7128-4c44-80db-51f83af8dc3e
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f9e4214-c090-4867-91a9-9d08c9656f7c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7eee4f6f-eb67-482e-8631-ffe2d2015b13
        userCondition: null
handle: standardHero
hasTitleField: false
icon: null
name: 'Standard Hero'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
