headingLevels:
  - 2
  - 3
  - 4
  - 5
  - 6
name: Full
options:
  image:
    toolbar:
      - imageTextAlternative
      - imageEditor
  link:
    decorators:
      isExternal:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in a new tab'
        mode: manual
  mediaEmbed:
    previewsInData: true
toolbar:
  - heading
  - '|'
  - numberedList
  - bulletedList
  - bold
  - italic
  - link
  - insertImage
  - undo
  - redo
  - htmlEmbed
  - mediaEmbed
  - sourceEditing
