fieldLayouts:
  3029a860-09a3-4562-9ce4-2e8580d699ef:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-18T18:25:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0587c309-76fe-4928-9be3-cb2980b7908c # Content Designer
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5176da0a-a983-4645-8ec3-6ed239746a0c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-17T18:05:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dda90ee5-34f1-4059-82b8-e83b9a32b0c9 # Footer Columns
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ab1f14e-cc13-47de-9963-339d010c4ebc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 08ec1209-3049-4e39-9d53-da610da5d938
        userCondition: null
handle: footerContent
name: 'Footer Content'
sortOrder: 3
