defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1c4ecae7-1e89-4a49-bbb5-0f581ff3c960 # HENRY Page
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  52ff5c36-e87c-4674-8f10-76565b13abdf: # Padstone Craft 5
    enabledByDefault: true
    hasUrls: true
    template: _pages/entry.twig
    uriFormat: '{% if object.level == 0 %}{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: 2e693f05-ab86-4d08-ba05-fca26ac22cb3
type: structure
